# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test suite

on: [push, pull_request]

jobs:
  tests:
    name: Meteor package tests
    runs-on: ubuntu-latest
    # needs: [lintcode,lintstyle,lintdocs] # we could add prior jobs for linting, if desired
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-22-

      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v2
        with:
          meteor-release: '3.1.2'

      - run: |
          meteor npm install
          meteor npm run test:mocha

name: Test suite
